---
- name: example for conditional statements
  hosts: all
  vars:
    my_service: httpd
  task: 
    - name: "{{ my_service }} package is installed"
      yum:
        name: "{{ my_service }}"
      when: my_service is defined