---
- name: New user is created and
  hosts: all
  become: true
  vars:
    packages: 
      - nmap
      - httpd
      - php
      - mod_php
      - mod_ssl


  tasks: 
    - name: User gets created
      yum:
        name: "{{ user_name }} "
        state: present