---
- name: New user is created and
  hosts: Webserver
  become: true
  vars: 
    user_name: reza
  tasks: 
    - name: Load variable from encrypted file
      include_vars:
        file: secret
    - name: Disply the encrypted variable 
      debug:
        msg: "{{ secret }}"
    - name: User gets created
      user:
      name: "{{ user_name }}"
      state: present
    

# for run command
## ansible-playbook -e "username=student" example.yml