version: '3'
services:
  controller:
    image: traefik:v2.6
    deploy:
      mode: global
    command:
      - "--configFile=/traefik.yml"
    ports:
      - "8081:80"
      - "8088:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/traefik.yml:ro"
    networks:
      - application

networks:
  application:
    external: true
