variables:
  REGISTRY: "reg.vajab.ir:8443/library/"
  IMAGE: "vajab_client"
  # ? what else could be used instead a simple string
  # ? Branch name?
  # TAG: "${CI_COMMIT_SHORT_SHA}"
  TAG: "testing"

stages: # List of stages for jobs, and their order of execution
- build
- deploy
- clean

build-job: # This job runs in the build stage, which runs first.
  stage: build
  script:
  - echo "Compiling the code..."
  - cd  $CI_PROJECT_DIR
  # TODO: change the branch name as a variable
  - git clone -b develop git@git.vajab.ir:$CI_PROJECT_PATH

deploy-job: # This job runs in the build stage, which runs first.
  stage: deploy
  script:
  - cd  $CI_PROJECT_DIR
  - ansible-playbook -i ./deploy/invent.ini --extra-vars "registry=$REGISTRY image=$IMAGE tag=$TAG project_path=$CI_PROJECT_DIR project_name=$CI_PROJECT_NAME" ./deploy/run.yaml

clean-job: # This job runs in the build stage, which runs first.
  stage: clean
  script:
  - rm -rf $CI_PROJECT_DIR
