version: '3'
services:
  reverse-proxy: 
    image: traefik:v2.4
    ports:
      - 80:80
      - 443:443
      - 8080:8080 #Management UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./mycert.crt:/etc/traefik/certs/mycert.crt
      - ./mycert.key:/etc/traefik/certs/mycert.key
      - ./traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml

  webservice:
    image: nginx:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.weebservice.rule=Host(`webservice.softgrand.ir`)"
      - "treafik.http.services.webservice.loadbalancer.service.port=8000"
      - "treafik.http.routers.webservice.entrypoint=websecure"
      - "traefik.http.routers.webservice.tls=true"

    ports:
      - 8000:80

  webservice1:
    image: nginx:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webservice1.rule=Host(`webservice1.softgrand.ir`)"
      - "treafik.http.services.webservice1.loadbalancer.service.port=8001"
      - "treafik.http.routers.webservice1.entrypoint=websecure"
      - "traefik.http.routers.webservice1.tls=true"
    ports:
      - 8001:80

