version: '3.7'
services:
  # ElastiFlow Unified Flow Collector
  flow-collector:
    image: elastiflow/flow-collector:5.3.5
    container_name: flow-collector
    restart: 'unless-stopped'
    volumes:
      - /etc/elastiflow:/etc/elastiflow
    network_mode: 'host'
    environment:
#      EF_FLOW_OUTPUT_ELASTICSEARCH_ADDRESSES: '127.0.0.1:9200'
#      EF_FLOW_OUTPUT_ELASTICSEARCH_USERNAME: 'admin'
#      EF_FLOW_OUTPUT_ELASTICSEARCH_PASSWORD: 'yXQsvvLi7QpfwUP5qIEt'
      EF_FLOW_OUTPUT_ELASTICSEARCH_ADDRESSES: 'localhost:9200,localhost:9300,localhost:9400'
      EF_FLOW_OUTPUT_ELASTICSEARCH_USERNAME: 'admin'
      EF_FLOW_OUTPUT_ELASTICSEARCH_PASSWORD: 'G4RbfwetB65fj2'
      EF_FLOW_SERVER_UDP_IP: '0.0.0.0'
      EF_FLOW_SERVER_UDP_PORT: 9995
      EF_FLOW_DECODER_ENRICH_IPADDR_METADATA_ENABLE: 'true'
#      EF_FLOW_DECODER_ENRICH_DNS_ENABLE: 'true'
#      EF_FLOW_DECODER_ENRICH_DNS_ENABLE: 'false'
#      EF_FLOW_DECODER_ENRICH_DNS_NAMESERVER_IP: '8.8.8.8'
#      EF_FLOW_DECODER_ENRICH_DNS_NAMESERVER_TIMEOUT: 10
      EF_FLOW_DECODER_ENRICH_MAXMIND_ASN_PATH: 'maxmind/GeoLite2-ASN.mmdb'
      EF_FLOW_DECODER_ENRICH_MAXMIND_ASN_ENABLE: 'true'
      EF_FLOW_DECODER_ENRICH_MAXMIND_GEOIP_PATH: 'maxmind/GeoLite2-City.mmdb'
      EF_FLOW_DECODER_ENRICH_MAXMIND_GEOIP_ENABLE: 'true'
      EF_FLOW_DECODER_ENRICH_RISKIQ_ASN_ENABLE: 'false'
      EF_FLOW_DECODER_ENRICH_RISKIQ_THREAT_ENABLE: 'false'
      EF_FLOW_OUTPUT_ELASTICSEARCH_ENABLE: 'true'
      EF_FLOW_OUTPUT_ELASTICSEARCH_ECS_ENABLE: 'false'
      EF_FLOW_OUTPUT_ELASTICSEARCH_TLS_ENABLE: 'true'
      EF_FLOW_OUTPUT_ELASTICSEARCH_TLS_SKIP_VERIFICATION: 'true'
      EF_FLOW_OUTPUT_ELASTICSEARCH_TLS_CA_CERT_FILEPATH: '/etc/elastiflow/ssl/ca.cert'
      EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_SHARDS: 1
      EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_REPLICAS: 1
      EF_FLOW_DECODER_ENRICH_RISKIQ_THREAT_ENABLE: 'false'
      EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_ENABLE: 'true'
      EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_OVERWRITE: 'true'
      EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_ISM_POLICY: 'hot-wam-delete-netflow'
      EF_FLOW_OUTPUT_STDOUT_ENABLE: 'false'
      EF_FLOW_OUTPUT_STDOUT_FORMAT: 'json_pretty'
      EF_FLOW_OUTPUT_ELASTICSEARCH_BATCH_MAX_BYTES: 3000000
      EF_FLOW_OUTPUT_ELASTICSEARCH_BATCH_DEADLINE: 1000
      EF_FLOW_DECODER_ENRICH_NETIF_GET_ATTRS: 'true'
      EF_FLOW_DECODER_ENRICH_SNMP_ENABLE: 'true'
      EF_FLOW_DECODER_ENRICH_SNMP_COMMUNITY: 'comunity snmp'
      EF_FLOW_DECODER_ENRICH_SNMP_TIMEOUT: 1
      EF_FLOW_DECODER_ENRICH_NETIF_CACHE_SIZE: 8000000000
      EF_FLOW_DECODER_ENRICH_DROP_FIELDS: 'flow.client.host.name,flow.dst.host.name,flow.end.sysuptime,flow.end.timestamp,flow.export.sysuptime,flow.server.host.name,flow.src.host.name'
