apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-affinity
  labels:
    name: myapp-pod-affinity
spec:
  containers:
  - name: data-process
    image: data-process
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: in
                values:
                  - Large
                  - Medium

