apiVersion: batch/v1
kind: CronJob
metadata:
  name: helloworld-cron
spec:
  schedule: "* * * * *" # min, hour, day_of_the_month, month, day_of_the_week
  #schedule: "30 * * * *" # 30 min everdays, 30 days
  #schedule: "30 * * * 1,2,3" # 1 sunday, 2 monday, 3 thursday,
  #schedule: "@hourly"
  #schedule: "@weekly
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox
            command: ["echo", "Hello Kubernetes!!!"]
          restartPolicy: Never